In [3]:
import numpy as np

In [5]:
from sklearn.model_selection import train_test_split#cross_validation=model_selection

In [7]:
X,y=np.arange(10).reshape((5,2)),range(5)#first part before comma belong to X and after that it belong to y

In [8]:
X

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [9]:
list(y)

[0, 1, 2, 3, 4]

In [16]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [17]:
X_train

array([[6, 7],
       [8, 9],
       [4, 5]])

In [18]:
Y_train

[0, 4, 2]

In [19]:
X_test

array([[0, 1],
       [2, 3]])

In [20]:
Y_test

[1, 3]

In [22]:
model.fit(X_train,y_train)
predictions=model.predict(X_test)

NameError: name 'model' is not defined