In [1]:
import numpy as np

In [5]:
arr=np.arange(25)

In [6]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [7]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [8]:
arr=np.arange(11)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[8]

8

In [11]:
arr[1:5]

array([1, 2, 3, 4])

In [12]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [13]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [14]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [15]:
arr[0:5]=100#0 t0 5 arrangge 100

In [16]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [17]:
arr=np.arange(11)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr1=arr[:6]

In [20]:
arr1

array([0, 1, 2, 3, 4, 5])

In [21]:
arr1[:]=99

In [22]:
arr1

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [24]:
arr_copy=arr.copy()

In [25]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [26]:
arr_copy[:]=50

In [27]:
arr_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [28]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [1]:
import numpy as np

In [2]:
arra_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [4]:
arra_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [5]:
arra_2d[0][0]

5

In [6]:
arra_2d[0]

array([ 5, 10, 15])

In [7]:
arra_2d[1,0]#row,column we can also write using comma

20

In [8]:
arra_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [13]:
arra_2d[:,1:]

array([[10, 15],
       [25, 30],
       [40, 45]])

In [14]:
arra_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [15]:
arra_2d[:,2:]

array([[15],
       [30],
       [45]])

In [16]:
arr=np.arange(1,11)

In [17]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
bool_arr=arr>5

In [19]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [20]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [21]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [22]:
arr[arr<3]

array([1, 2])

In [23]:
arra_2d=np.arange(50).reshape(5,10)

In [24]:
arra_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [26]:
arra_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Array operation
### array with array
### array with scalars
### universal array functions

In [27]:
import numpy as np

In [28]:
arr=np.arange(11)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [34]:
arr+200

array([200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210])

In [35]:
arr-100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [36]:
arr/arr

C:\Users\manisha\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [37]:
1/arr

C:\Users\manisha\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [38]:
arr**2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [39]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [40]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [41]:
np.max(arr)

10

In [42]:
arr.max()

10

In [43]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [44]:
np.log(arr)

C:\Users\manisha\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

## exercise

In [1]:
import numpy as np

In [3]:
arr=np.zeros(10)

In [4]:
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10,5)#or np.ones(10)*5

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [9]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [10]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.random.rand(1)

array([0.89316583])

In [31]:
np.random.randn(25)

array([ 0.38698102, -2.02388757,  1.08993091,  0.29805847, -0.03132415,
       -1.29711745,  0.12315018, -1.80003602,  0.38143365, -1.51290509,
       -1.07371202,  0.77845872, -1.12997907, -1.3247006 , -1.74745808,
        0.88395784,  0.50282999,  1.75482272,  0.59200574, -0.20888872,
        0.62150374, -0.03599499, -0.50418883, -0.66217965, -1.79262555])

In [32]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [33]:
np.linspace(0.01,1,100).reshape(10,10)


array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [23]:
mat=np.arange(1,26).reshape(5,5)

In [24]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [34]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [35]:
mat[3,4]

20

In [37]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [38]:
mat[4]

array([21, 22, 23, 24, 25])

In [39]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat.sum()

325

In [41]:
np.std(mat)

7.211102550927978

In [45]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])